name: CI

permissions:
  contents: read
  checks: write
  issues: write

on:
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  tests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Prepare log directory
        run: mkdir -p build/logs

      - name: PHP-CS-Fixer
        run: >-
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --allow-risky=yes --using-cache=no --dry-run --diff

      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse --configuration=phpstan.neon.dist --error-format=table \
            | tee build/logs/phpstan-${{ matrix.php }}.log

      - name: PHPUnit
        run: vendor/bin/phpunit --log-junit build/logs/phpunit-${{ matrix.php }}.xml

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-php-${{ matrix.php }}
          path: build/logs/
          retention-days: 7

  quality-report:
    name: Quality Report
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: test-results-php-*
          merge-multiple: true

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
          check_run: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository ? 'false' : 'true' }}
          comment_mode: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository ? 'always' : 'off' }}
